service: tracktime-api

provider:
  name: aws
  profile: serverless-admin
  runtime: nodejs4.3
  region: ap-southeast-2
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: sessions
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: sessions
          method: get
          cors: true
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: sessions/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: sessions/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: sessions/{id}
          method: delete
          cors: true

resources:
  Resources:
    TrackTimeSessionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'tt-sessions'
